name: trackit
description: TrackIt - College Bus Tracker
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.4.0
  url_launcher: ^6.1.11
  geolocator: ^9.0.2
  # firebase_core: ^2.8.0
  # cloud_firestore: ^4.7.0
  # firebase_messaging: ^14.4.1
  # Temporarily disabled desktop/local-notifications plugin to avoid desktop build issues:
  # flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test: # <-- MOVED HERE
    sdk: flutter
  flutter_lints: ^2.0.0 # <-- Add this line to follow standard Flutter projects (recommended)
  csv: ^5.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/tracki_logo.jpg
  # flutter_test: <-- Removed from here
